# macOS Dev: PostgreSQL + msfconsole image, Elixir runs on host
# Usage:
#   docker compose -f compose.macos.dev.yaml up --build -d
#   mix setup
#   mix phx.server
#
# Limitations:
#   - msfconsole containers have limited network functionality
#
# Configuration: Copy msfailab.conf.example to .env and edit as needed.

services:
  postgres:
    image: postgres:17
    container_name: msfailab-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      # Bind to localhost only - not exposed to LAN
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - msfailab
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  msfconsole-image:
    build: ./msfconsole
    image: msfailab-msfconsole
    command: ["true"]
    networks:
      - msfailab

volumes:
  postgres_data:

networks:
  msfailab:
    name: msfailab
