# Linux Dev: PostgreSQL + msfconsole image, Elixir runs on host
# Usage:
#   docker compose -f compose.linux.dev.yaml up --build -d
#   mix setup
#   mix phx.server
#
# Configuration: Copy msfailab.conf.example to .env and edit as needed.

services:
  postgres:
    image: postgres:17
    container_name: msfailab-postgres
    network_mode: host
    # Bind to localhost only - not exposed to network
    command: postgres -c listen_addresses=localhost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  msfconsole-image:
    build: ./msfconsole
    image: msfailab-msfconsole
    command: ["true"]
    network_mode: host

volumes:
  postgres_data:
