name: CI

on:
  pull_request:
    branches: [main]

env:
  MIX_ENV: test

jobs:
  precommit:
    runs-on: docker
    container:
      image: hexpm/elixir:1.19.2-erlang-28.1.1-debian-trixie-20251117-slim
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: msfailab_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git nodejs npm

      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('mix.lock') }}
          restore-keys: mix-

      - name: Install Hex and Rebar
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Install dependencies
        run: mix deps.get

      - name: Run precommit
        run: mix precommit
        env:
          DATABASE_URL: ecto://postgres:postgres@postgres/msfailab_test
