import Config

# Configure your database
config :msfailab, Msfailab.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "msfailab_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :msfailab, MsfailabWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ttTUGbuNFEBw1rAkiWuHfUqf94SdeTRv2Z9RRSXu7x5Azhf2L1ME4NctBITX1Ndc",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:msfailab, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:msfailab, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :msfailab, MsfailabWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/msfailab_web/router\.ex$",
      ~r"lib/msfailab_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :msfailab, dev_routes: true

# Development logging: stdout + file
# Console output uses simple format, file gets same format
config :logger, :default_formatter, format: "$time [$level] $message [$metadata]\n"

# Enable SASL reports (supervisor crash reports, progress reports)
# This is critical for seeing WHY processes crash
config :logger,
  handle_sasl_reports: true,
  # Also translate OTP reports to Logger format
  handle_otp_reports: true

# File handler for dev - logs to log/app.log alongside console output
# Uses :all metadata to capture everything for debugging
config :msfailab, :logger, [
  {:handler, :app_log, :logger_std_h,
   %{
     config: %{
       file: ~c"log/app.log",
       filesync_repeat_interval: 5000,
       file_check: 5000,
       max_no_bytes: 10_000_000,
       max_no_files: 5
     },
     formatter:
       Logger.Formatter.new(format: "$time [$level] $message [$metadata]\n", metadata: :all)
   }}
]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Docker development settings
# In development, Elixir runs on host so we need port mapping to reach MSF RPC
config :msfailab,
  env: :dev,
  docker_rpc_mode: :port_mapping
